# Generated by Django 2.0.7 on 2018-07-16 16:47
# Generated using the command 'manage.py makemigrations polls'
# That command should probably be re-run every time you update your models for the relevant app
# anyway, this reads in all the model files and creates a migration (i.e. database config update)
# to incorporate your new data structure
# re-running it will create a new migrations script which will update the database accordingly
# the default file name '0001_initial.py' seems to be the standard migration file naming convention
# the actual migration is done with 'manage.py migrate'

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
